import type { Metadata } from "next";
import { ThemeSwitcher } from "@/components/theme/ThemeSwitcher";
import "@/components/theme/globals.css";
import { satoshi } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Lapo - CoreInfra Assessment",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
    apple: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable} antialiased`}>
        {children}
        <ThemeSwitcher />
      </body>
    </html>
  );
}
